[BotConfig]
Protocol = "AndroidPhone"
TryReconnect = true
# CustomHost = 
HighwayChunkSize = 4096
EnableAudio = false
DefaultTimeout = 6000

[BotDevice.Model]
Name = "Konata A614D4D3"
Manufacturer = "Konata Project"
Imei = "82035139341196"
Imsi = "548373102239410"
BaseBand = "KONATA.CORE.A9EB.1.0.REV"
CodeName = "REL"

[BotDevice.Display]
Width = 1080
Height = 1920

[BotDevice.System]
Name = "konata"
Type = "android"
Version = "9.0.1"
BootId = "46291085605e8928"
BootLoader = "KONATA.CORE.EA608408.BOOTLOADER_1_0"
AndroidId = "eb9019fde33fdc81"
Incremental = "040c54c0fd398a51"
InnerVersion = "KONATA.CORE.USERDEBUG.9.0.1"
FingerPrint = "konata/core/konata:9.0.1/72368229:user/release-keys"
Guid = "sbd+Gdd11kq5/uT5vE3r8w=="

[BotDevice.Network]
NetType = 2
NetApn = "CMNET"
NetOperator = "China Mobile"
NetIpAddress = "AAAAAA=="
WifiMacAddress = "qrvM3e4="
WifiSsid = "<Hidden SSID>"
WifiBssid = "qrvM3e4="

[System]
Extensions = [
]

[System.Ping]
NeedAt = true
Request = "ping"
Response = "Pong!"
